<?php
/**
 * @var $block \BroSolutions\OrdersOverview\Block\Adminhtml\Menu
 */
?>

<div class="nav-panel">
    <nav class="navigation-menu" data-action="navigation">
        <ul id="menu" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left+10 top+30"}}}'>
            <?php foreach ($block->getOrderTypes() as $type):?>
                <li class="level0 level-top ui-menu-item">
                    <a href="<?= $block->getPageUrl($type['url']) ?>"><?= $block->escapeHtml(__($type['title'])) ?><i class="arrow right"></i></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </nav>
</div>
